### ISSUE TITLE
Files without ID3 tag are not processed

### ISSUE THREAD

**Issue by JoostvL** [PsynApps/estimpy#2]
E:\Out\EstimPy>python visualizer.py -wm -i  ./testmp3/* -r
./testmp3\input.mp3...Traceback (most recent call last):
  File "E:\Out\EstimPy\visualizer.py", line 62, in <module>
    es_audio = es.audio.Audio(file=file)
  File "E:\Out\EstimPy\estimpy\audio.py", line 42, in __init__
    file_metadata = es.metadata.Metadata(file=file)
  File "E:\Out\EstimPy\estimpy\metadata.py", line 57, in __init__
    self.load()
    ~~~~~~~~~^^
  File "E:\Out\EstimPy\estimpy\metadata.py", line 149, in load
    metadata = MetadataFormatMP3.load(self.file)
  File "E:\Out\EstimPy\estimpy\metadata.py", line 217, in load
    file_tags = cls._load_file_tags(file)
  File "E:\Out\EstimPy\estimpy\metadata.py", line 285, in _load_file_tags
    return mutagen.id3.ID3(file)
           ~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\id3\_file.py", line 76, in __init__
    super(ID3, self).__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\id3\_tags.py", line 175, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\_util.py", line 534, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\_tags.py", line 110, in __init__
    self.load(*args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\id3\_file.py", line 151, in load
    self._header = ID3Header(fileobj)
                   ~~~~~~~~~^^^^^^^^^
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\epson\AppData\Local\Programs\Python\Python313\Lib\site-packages\mutagen\id3\_tags.py", line 66, in __init__
    raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
mutagen.id3._util.ID3NoHeaderError: './testmp3\\input.mp3' doesn't start with an ID3 tag

**Comment by JoostvL** [comment]
For now I changed line 285 in Metadata.py to:
    return file

Fixes my issue and does the same thing. (My Python skills do not include and if empty, than :D  )
